version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - frontend
    volumes:
      - ./backend:/app/messaging/backend

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app/messaging/frontend
