version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
    volumes:
      - ./backend:/app/messaging

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app/messaging
