version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    volumes:
      - .:/app/messaging

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8000:8000"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #   volumes:
  #     - ./frontend:/app/messaging
