version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./env
    volumes:
      - ./backend:/app/messaging

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8000:8000"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #   volumes:
  #     - ./frontend:/app/messaging
